### ISSUE TITLE
Implement an API for different kinds of bookmarks

### ISSUE THREAD

**Issue by flaksp** [camellia-app/camellia#415]
Currently, there's only one bookmark kind, it's called a *Chip*:

<img width="100" alt="Screenshot 2023-02-23 at 20 12 43" src="https://user-images.githubusercontent.com/12474739/220980343-5062cda6-28a9-4203-909d-fff7b04a6cfb.png">

In the future we would like to introduce new kinds, e.g. this is how bookmarks in Safari look like:

<img width="483" alt="Screenshot 2023-02-23 at 20 14 45" src="https://user-images.githubusercontent.com/12474739/220980810-26fef354-17a8-4291-a52e-d541793b8ca3.png">

Actual list of new kinds will be described in other issues. This issue is about implementing a base that will be used for future kinds. It's important to note that some bookmark kinds may require specific requirements to be enabled, for example if we want to introduce new bookmark kind that has website preview, that we need to ask for additional permissions first (to screenshot pages and to store unlimited amount of data in the storage API).

```[tasklist]
### Blockers
- [ ] https://github.com/camellia-app/camellia/issues/31
```

```[tasklist]
### Tasks
- [ ] Implement an API that will allow to receive a style for specific category
- [ ] Support picking styles in categories options
```
